//
//  SFData.swift
//  SFTabBar
//
//  Created by Adam Jones on 9/29/20.
//

import UIKit
import SwiftUI

/// Generated by `Scripts/generate-symbols.py` from the installed SF Symbols app.
let symbolCatalog: SymbolCatalog = loadCatalog("symbols-catalog.json")

/// The categories, in Apple's display order.
let sflibrary: [Library] = symbolCatalog.sections

/// Loads the catalog, degrading to an empty one rather than crashing.
///
/// The browser showing nothing is a bad day; the app terminating the first time
/// someone taps an icon row is a worse one.
func loadCatalog(_ filename: String) -> SymbolCatalog {
    guard let file = Bundle.main.url(forResource: filename, withExtension: nil) else {
        assertionFailure("Couldn't find \(filename) in main bundle.")
        return .empty
    }

    do {
        let data = try Data(contentsOf: file)
        return try JSONDecoder().decode(SymbolCatalog.self, from: data)
    } catch {
        assertionFailure("Couldn't load \(filename):\n\(error)")
        return .empty
    }
}
